### ISSUE TITLE
Add <KeyInfo> to request signatures

### ISSUE THREAD

**Issue by camsaul** [metabase/saml20-clj#13]
It would be nice if signing requests included <KeyInfo> so we can include the SP's public key in the request so the IdP can use it to encrypt assertions if it doesn't already have a public key for us. Right now request signatures work but it's not including <KeyInfo>  yet

**Comment by dbrrr** [comment]
See: https://github.com/metabase/saml20-clj/pull/21

There are a number of fields which can be extracted using the X509KeyInfoFactory, including a cert chain, which could be exposed as config parameters. I'm not sure the added complexity is worth it for this use-case, though.

**Comment by camsaul** [comment]
Implemented in #21
